---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt: 
      update_cache: yes
    when: ansible_distribution in ['Debian','Ubuntu']

  - name: install apache2 and php package
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


